### ISSUE TITLE
translate3d mixin

### ISSUE THREAD

**Issue by gabrielperales** [Wakkos/Wakkos-CSS-Framework#30]
Se te ha colado *translate* en vez de *translate3d* en la linea 229 de _mixins.scss en este mixin:

    @mixin translate3d($x: 0, $y: 0, $z: 0) {
	    -webkit-transform : translate($x, $y, $z);
	    -moz-transform : translate($x, $y, $z);
	    -ms-transform : translate($x, $y, $z);
	    -o-transform : translate($x, $y, $z);
	    transform : translate($x, $y, $z);
    }

También creo que podrías refactorizar todos los mixins usando el mixin de vendor, quedando algo así:

    @mixin translate3d($x: 0, $y: 0, $z: 0) {
      @include vendor(transform, translate3d($x, $y, $z));
    }

no se si tendrías que escapar los $x, $y y $z, pero ahorras muchas lineas y así solo tienes que configurar los prefijos en el mixin vendor.

**Comment by Wakkos** [comment]
Cerrado.  Arreglado lo del 3D y quiero buscar una manera de poder mantener actualizados los prefijos. A lo mejor uso Codekit para eso.
